version: "3.8"
services:
    db:
        container_name: db
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=notesdb
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3306:3306
        volumes:
            - ./server/db:/db/data
        healthcheck:
            test: mysql notesdb --user=root --password='root' --silent --execute "SELECT 1;"
            interval: 30s
            timeout: 10s
            retries: 5   
    frontend:
        container_name: frontend_app
        build: ./frontend
        ports:
            - 3000:3000
    backend:
        depends_on:
            db:
                condition: service_healthy
        restart: always
        build: ./server
        ports:
            - 8080:5000

