version: "3.8"
services:
    db:
        container_name: db
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=notesdb
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3306:3306
        volumes:
            - ./server/db:/db/data

    frontend:
        container_name: frontend_app
        build: ./frontend
        ports:
            - 3000:3000
    backend:
        restart: always
        build: ./server
        ports:
            - 8080:5000
