version: "3.8"
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
        - '5432:5432'
        volumes: 
        - db:/var/lib/postgresql/data
    frontend:
        container_name: frontend_app
        build: ./frontend
        ports:
            - 3000:3000
    backend:
        depends_on:
          db:
            condition: service_healthy
        container_name: backend_app
        restart: always
        build: ./server
        ports:
            - 5000:5000
volumes:
  db:
    driver: local